'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeeMast
    Public Property Id As Integer
    Public Property Fname As String
    Public Property MName As String
    Public Property Lname As String
    Public Property DOB As Date
    Public Property PANno As String
    Public Property UANNo As String
    Public Property ESINo As String
    Public Property PFNo As String
    Public Property JoinofDate As Date
    Public Property city As String
    Public Property State As String
    Public Property Address As String
    Public Property pinCode As String
    Public Property Emailid As String
    Public Property BankName As String
    Public Property Accountno As String
    Public Property IFSCCode As String
    Public Property isactive As Nullable(Of Boolean)
    Public Property FYMasterFY As String
    Public Property DeptMastId As Integer
    Public Property EmpLevelId As Integer
    Public Property EmployerMast_cc1 As Integer

    Public Overridable Property DeptMast As DeptMast
    Public Overridable Property EmpLeaves As ICollection(Of EmpLeaf) = New HashSet(Of EmpLeaf)
    Public Overridable Property EmpLevel As EmpLevel
    Public Overridable Property EmployeeSalaryMasts As ICollection(Of EmployeeSalaryMast) = New HashSet(Of EmployeeSalaryMast)
    Public Overridable Property EmployerMast As EmployerMast
    Public Overridable Property FYMaster As FYMaster

End Class
