'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeeSalaryMast
    Public Property Id As Integer
    Public Property wfd As Date
    Public Property CTCMonthly As Double
    Public Property CTCYear As Double
    Public Property Fixcompamt As Double
    Public Property flexcompamt As Double
    Public Property EmployeeMastId As Integer
    Public Property FYMasterFY As String

    Public Overridable Property EmployeeMast As EmployeeMast
    Public Overridable Property EmpMonthlySalaries As ICollection(Of EmpMonthlySalary) = New HashSet(Of EmpMonthlySalary)
    Public Overridable Property EmpSalaryComponents As ICollection(Of EmpSalaryComponent) = New HashSet(Of EmpSalaryComponent)
    Public Overridable Property FYMaster As FYMaster

End Class
