'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmpMonthlySalary
    Public Property Id As Integer
    Public Property WorkingMonthDate As Date
    Public Property TotalDays As Short
    Public Property WorkingDays As Short
    Public Property LeaveDays As Short
    Public Property TotalSalaryAmount As Double
    Public Property OnhandAmount As Double
    Public Property Deductamount As Double
    Public Property EmployeeSalaryMastId As Integer

    Public Overridable Property EmployeeSalaryMast As EmployeeSalaryMast
    Public Overridable Property EmpMonthlyComponets As ICollection(Of EmpMonthlyComponet) = New HashSet(Of EmpMonthlyComponet)

End Class
