'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmpSalaryComponent
    Public Property Id As Integer
    Public Property Amount As Double
    Public Property EmployeeSalaryMastId As Integer
    Public Property SalaryComponentMastId As Integer

    Public Overridable Property EmployeeSalaryMast As EmployeeSalaryMast
    Public Overridable Property EmpMonthlyComponets As ICollection(Of EmpMonthlyComponet) = New HashSet(Of EmpMonthlyComponet)
    Public Overridable Property SalaryComponentMast As SalaryComponentMast

End Class
