'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FYMaster
    Public Property FY As String

    Public Overridable Property EmployeeMasts As ICollection(Of EmployeeMast) = New HashSet(Of EmployeeMast)
    Public Overridable Property EmployeeSalaryMasts As ICollection(Of EmployeeSalaryMast) = New HashSet(Of EmployeeSalaryMast)
    Public Overridable Property EmployerMasts As ICollection(Of EmployerMast) = New HashSet(Of EmployerMast)
    Public Overridable Property HolidaysMasts As ICollection(Of HolidaysMast) = New HashSet(Of HolidaysMast)
    Public Overridable Property LeaveMasts As ICollection(Of LeaveMast) = New HashSet(Of LeaveMast)

End Class
