'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HolidaysMast
    Public Property Id As Integer
    Public Property HolidaysName As String
    Public Property HolidaysDate As Date
    Public Property wfd As Date
    Public Property FYMasterFY As String
    Public Property EmployerMast_cc As Integer

    Public Overridable Property EmployerMast As EmployerMast
    Public Overridable Property FYMaster As FYMaster

End Class
