'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LeaveMast
    Public Property Id As Integer
    Public Property LeaveName As String
    Public Property NoofDays As Nullable(Of Integer)
    Public Property wfd As Date
    Public Property FYMasterFY As String
    Public Property EmployerMast_cc As Integer

    Public Overridable Property EmpLeaves As ICollection(Of EmpLeaf) = New HashSet(Of EmpLeaf)
    Public Overridable Property EmployerMast As EmployerMast
    Public Overridable Property FYMaster As FYMaster

End Class
