'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SalaryComponentMast
    Public Property Id As Integer
    Public Property wfd As Date
    Public Property Name As String
    Public Property CompType As Comptype
    Public Property TypeRsPer As TypePerRs
    Public Property amount As Double
    Public Property basedoncomponent As Nullable(Of Integer)
    Public Property Compcalcutiontype As Addmine

    Public Overridable Property EmpSalaryComponents As ICollection(Of EmpSalaryComponent) = New HashSet(Of EmpSalaryComponent)

End Class
