'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class View_2
    Public Property EmployeeSalaryMastsid As Integer
    Public Property EmployeeSalaryMastswfd As Date
    Public Property CTCMonthly As Double
    Public Property CTCYear As Double
    Public Property Fixcompamt As Double
    Public Property flexcompamt As Double
    Public Property EmployeeMastId As Integer
    Public Property FYMasterFY As String
    Public Property EmpSalaryComponentsid As Integer
    Public Property EmpSalaryComponentsamount As Double
    Public Property EmployeeSalaryMastId As Integer
    Public Property SalaryComponentMastId As Integer
    Public Property SalaryComponentMastsid As Integer
    Public Property Name As String
    Public Property CompType As Integer
    Public Property TypeRsPer As Integer
    Public Property amount As Double
    Public Property basedoncomponent As Nullable(Of Integer)
    Public Property Compcalcutiontype As Integer

End Class
